/**
 * BITV-Kategorien und deren Zuordnungen
 */

const { BITV_CATEGORIES } = require('../constants');

const bitvCheckCategories = {
  '1.1.1a': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.1.1c': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.1.1d': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.2.1': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.2.2': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.2.3': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.2.4': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.2.5': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.3.1a': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.3.1b': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.3.1c': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.3.1e': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.3.1f': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.3.1g': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.3.1h': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.4.1': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.4.2': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.4.3': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.4.4': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.4.5': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.4.6': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.4.7': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.4.8': BITV_CATEGORIES.WAHRNEHMBAR,
  '1.4.9': BITV_CATEGORIES.WAHRNEHMBAR,
  '2.1.1': BITV_CATEGORIES.BEDIENBAR,
  '2.1.2': BITV_CATEGORIES.BEDIENBAR,
  '2.2.1': BITV_CATEGORIES.BEDIENBAR,
  '2.2.2': BITV_CATEGORIES.BEDIENBAR,
  '2.4.1': BITV_CATEGORIES.BEDIENBAR,
  '2.4.2': BITV_CATEGORIES.BEDIENBAR,
  '2.4.3': BITV_CATEGORIES.BEDIENBAR,
  '2.4.4': BITV_CATEGORIES.BEDIENBAR,
  '2.4.5': BITV_CATEGORIES.BEDIENBAR,
  '2.4.6': BITV_CATEGORIES.BEDIENBAR,
  '2.4.7': BITV_CATEGORIES.BEDIENBAR,
  '3.1.1': BITV_CATEGORIES.VERSTAENDLICH,
  '3.1.2': BITV_CATEGORIES.VERSTAENDLICH,
  '3.1.3': BITV_CATEGORIES.VERSTAENDLICH,
  '3.1.4': BITV_CATEGORIES.VERSTAENDLICH,
  '3.2.1': BITV_CATEGORIES.VERSTAENDLICH,
  '3.2.2': BITV_CATEGORIES.VERSTAENDLICH,
  '3.2.3': BITV_CATEGORIES.VERSTAENDLICH,
  '3.2.4': BITV_CATEGORIES.VERSTAENDLICH,
};

module.exports = bitvCheckCategories;